config/routes.rb
Rails.application.routes.draw do

  # get 'dashboard/index'

  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: "dashboard#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :computers do
    resources :bookings, only: [:show, :create]
  end

  resources :bookings, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :computer
end

app/models/computer.rb
class Computer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = current_user.bookings.last
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @computer = Computer.find(params[:computer_id])
    @booking.computer = @computer
    if @booking.save!
      redirect_to dashboard_path
    else
      render "computers/show", status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to dashboard_path, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @computer = Computer.find(params[:id])
    @booking = Booking.new

    @marker =
      [{
        lat: current_user.latitude,
        lng: current_user.longitude
      }]
  end

  def new
    @computer = Computer.new
  end

  def create
    @computer = Computer.new(computer_params)
    @computer.user = current_user
    @computer.save!
    redirect_to dashboard_path
  end

  def edit
    @computer = Computer.find(params[:id])
  end

  def update
    @computer = Computer.find(params[:id])
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to computer_url(@computer), notice: "Computer was successfully updated." }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @computer = Computer.find(params[:id])
    @computer.destroy
    redirect_to dashboard_path, status: :see_other
  end


  private

  def computer_params
    params.require(:computer).permit(:brand, :model, :year, :screen_size , :processor, :ram,  :storage, :category, :os, :price, :description, photos: [])

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @bookings = Booking.all
    @computers = Computer.all
  end


  def show
    @booking = current_user.bookings.last
    @bookings = current_user.bookings
    @computers = Computer.all
    @computer = Computer.last
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @computers = Computer.all
    if params[:query].present?
      sql_query = "brand ILIKE :query OR model ILIKE :query OR category ILIKE :query"
      @computers = Computer.where(sql_query, query: "%#{params[:query]}%")
    else
      @computers = Computer.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<br>
<br>

<br>

  <div class="bookingform  ">
    <%# update a new booking  %>
    <h1>Update your booking</h1>

      <%= simple_form_for [ @booking] do |f| %>
        <%# <%= f.input :brand %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <div class="row" id="book">
          <%= f.submit class: "btn btn-flat" %>
          <% end %>
        </div>
  </div>
</div>

app/views/bookings/show.html.erb
<br>
<br>
<div class="container">
<div class="row">
  <h1> Welcome <%= current_user.first_name.capitalize  %> to your bookings!</h1>
</div>
<div class="card" id="bookingcard">
  <h3><%= @booking.computer.brand  %></h3>
</div>
<div class="card" id="bookingcard">
  <ul>
    <li>Start Date: <%= @booking.start_date %></li>
    <li>End Date: <%= @booking.end_date %></li>
    </div>
</div>
</ul>
    <div class="col d-flex justify-content-center"  >
    <%= link_to "Back to Computers list", computers_path, class: "btn btn-flat" %>
  </div>
</div>
<br>
<br>

app/views/computers/_form.html.erb
  <%= simple_form_for(@computer) do |f| %>
    <%#= f.error_notification %>
    <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.input :brand %>
      <%= f.input :model %>
      <%= f.input :year, placeholder: "2000", input_html: { min: 2000, max: 2022 } %>
      <%= f.input :screen_size, label: "Screen size (inches)", collection: [10.1, 11.6, 12.5, 13.0, 13.3, 14.0, 15.0, 15.6, 17.3] %>
      <%= f.input :processor %>
      <%= f.input :ram, label: "RAM" %>
      <%= f.input :storage %>
      <%= f.input :os, label: "OS", collection: ["Windows", "Mac OS", "Linux", "Ubuntu", "Fedora", "FreeBSD"] %>
      <%= f.input :category, collection: ["Data Science", "Development", "Documentation", "Entertainment", "Gaming", "General Use", "Photo-Editing", "Video-Editing"] %>
      <%= f.input :price, label: "Price (€ per day)", input_html: { min: "0"}  %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.input :description, input_html: { maxlength: 500 } %>
    <br>
    <div class="d-flex justify-content-around align-items-center">
      <%= f.button :submit, "Post your laptop", class: "w-50 btn btn-flat" %>
      <%= link_to "Back to computers", computers_path, class: "btn btn-outline-secondary" %>
    </div>
  <% end %>

app/views/computers/edit.html.erb
<div class="form-container">
  <div class="form-card p-5">

    <h3>Edit your computer details</h3>
    <%= render "form", computer: @computer %>
    <br>
  </div>
</div>

app/views/computers/index.html.erb
<div class="container">
  <div class="index-container">
    <h1>Available Computers</h1>
  <%= render "pages/searchbar", computers: @computers %>
    <div class="row d-flex justify-content-center">
      <% @computers.each do |computer| %>
        <div class="col-3 mb-3 mx-3">
          <div class="card h-100 d-flex row justify-content-center">

            <% computer.photos.each do |photo| %>
              <%= cl_image_tag photo.key, width: 400, height: 300, crop: :fill %>
            <% end %>
            <ul>
              <li> <%= computer.brand %> </li>
              <li> Useful for <%= computer.category %> </li>
              <li> <%= computer.screen_size %> inches </li>
              <li> <%= computer.price %> €/day </li>
            </ul>
            <div>
              <%= link_to "See more", computer_path(computer), class: "btn btn-flat" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/computers/new.html.erb
<div class="container d-flex justify-content-center">

  <div class="form-container">
    <div class="row form-inputs">

    <h3>Add a new laptop</h3>
    <div>
      <%= render "form", computer: @computer %>
    </div>
  </div>
</div>

app/views/computers/show.html.erb
<div class="container">

  <div class="title-wrapper mb-4">
    <h1><%= @computer.brand %> <%= @computer.model %></h1>
    <h3>Owner: <%= @computer.user.first_name %> <%= @computer.user.last_name %>&nbsp

    <% if @computer.user.photo.present? %>
      <%= image_tag @computer.user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    </h3>

  </div>

    <div class="carousel-wrapper">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <% @computer.photos.each_with_index do |photo, i| %>
            <div class="carousel-item <%= i == 0 ? "active" : "" %>">
              <%= cl_image_tag photo.key, class: "carousel-img"  %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>


   <div class="show-body-wrapper">

    <div class="details_card w-100 px-4">
      <ul>
      <h3 class="mb-3" style="text-align: left">Specs</h3>
        <li class="spec-list"><strong>Year: </strong><%= @computer.year %></li class="spec-list">
        <li class="spec-list"><strong>Screen size: </strong><%= @computer.screen_size %> inches </li class="spec-list">
        <li class="spec-list"><strong>Processor: </strong><%= @computer.processor %></li class="spec-list">
        <li class="spec-list"><strong>Ram: </strong><%= @computer.ram %></li class="spec-list">
        <li class="spec-list"><strong>Storage: </strong><%= @computer.storage %></li class="spec-list">
        <li class="spec-list"><strong>OS: </strong><%= @computer.os %></li class="spec-list">
        <li class="spec-list"><strong>Category: </strong><%= @computer.category %></li class="spec-list">
        <p class="spec-list pt-3"><%= @computer.description %></p>
        <li class="spec-list pt-3" style="list-style: none"><h3 class="details-price" style="text-align: right"><%= @computer.price %> €/day</h3></li>
      </ul>
    </div>

  <div class="bookingform w-100">
    <h2><strong>Book this laptop</strong></h2>
    <%= simple_form_for [@computer, @booking] do |f| %>
      <h4><strong><%= f.input :start_date  %></strong></h4>
      <br>
      <h4><strong><%= f.input :end_date %></strong></h4>
      <br>
      <div class="btn_form_book">
        <%= f.submit class: "btn btn-flat mt-4" %>
      </div>
    <% end %>
  </div>

 </div>


<div class="w-100 mt-3">
  <div class="container-map w-100"
    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="container dashboard">
  <h3>My Renting Dashboard</h3>
    <div class="computers-container">
      <div class ="no-hover d-flex justify-content-around">
        <div>
              <h3> My Computer </h3>
              <div class="row computers-box">
                <div class="col">
                  <% @computer.photos.each do |photo| %>
                      <%= cl_image_tag photo.key, width: 300, height: 250, crop: :fill  %>
                  <% end %>
                </div>
                <div class="col">
                  <ul>
                  <li><%= @computer.brand %> </li>
                  <li> <%= @computer.model %> </li>
                  <li><strong><%= @computer.price %> €/day </strong></li>
                  </ul>
                </div>
                <div class="col icon d-flex flex-column justify-content-between">
                  <%= link_to "",  new_computer_path, class: "fa-solid fa-circle-plus d-block" %>
                  <%= link_to "",  edit_computer_path(@computer), class: "fa-solid fa-pencil d-block" %>
                  <%= link_to "", computer_path(@computer), class: "fa-solid fa-trash-can d-block", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                </div>
              </div>
          </div>
      </div>
    </div>
    <div class="bookings-computer">
      <div class="no-hover d-flex justify-content-around">
      <div>
        <h3> My Bookings </h3>
        <div class="row booking-box">
          <div class="col">
          <% @bookings.each do |booking| %>
            <li> Start Date : <%= booking.start_date  %></li>
            <li> End Date :  <%= booking.end_date %> </li>
            <% start = booking.start_date %>
            <% last = booking.end_date %>
            <% result = last - start %>
            <% price = result.to_i * @computer.price %>
            <li> Number of Days : <%= result.to_i %> days</li>


              <h5 class ="balance">Balance : <strong><%= price %> Euros</strong> </h5>
            
          </div>
            <div class=" col icon d-flex flex-column justify-content-between align-items-center">
              <%= link_to "",   edit_booking_path(booking), class: "fa-solid fa-pencil d-block" %>
              <%= link_to "",   booking_path(booking), class: "fa-solid fa-trash-can d-block", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Computer-Swap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body data-controller="navbar">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <div class="<% unless controller.controller_name == "pages" && controller.action_name == "home" %>mt-5<% end %>">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_searchbar.html.erb
<div class="search-form-control form-group">
  <%= form_with url: root_path(anchor: "computers-anchor"), method: :get, class: "d-flex", data: {turbo: false}  do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a laptop"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1548611635-b6e7827d7d4a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80);" data-navbar-target="banner">
  <div class="container">
    <h1 id="titlehome" >Computer-Swap allows <strong>you</strong> to rent laptops !</h1>
      <p>Choose your computer depending on your needs of <span data-controller="typed-js"></span></p>
      <a class="btn btn-primary" href="#computers-anchor" role="button">Start browsing</a>
  </div>
</div>
<div class="steps-container">
<div class="card" id="card1" style="width: 18rem;">
  <h3>Choose it</h3>
  <img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text"> Explore our catalog of available laptops</p>
  </div>
</div>
<div class="card" id="card1" style="width: 18rem;">
  <h3>Book it</h3>
  <img src="https://res.cloudinary.com/carole-g/image/upload/v1661286242/booking_sb1pii.avif" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text"> Book the computer you need, when you need it</p>
  </div>
</div>
<div class="card" id="card1" style="width: 18rem;">
  <h3>Bring it back</h3>
  <img src="https://images.unsplash.com/photo-1522201949034-507737bce479?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text"> Bring the computer back to the owner</p>
  </div>
</div>
</div>


<div class="container" id="computers-anchor">
  <div class="index-container" id='startBrowsing'>
    <h1>Available Computers</h1>
  <%= render "searchbar", computers: @computers %>
    <div class="cards">
      <% @computers.each do |computer| %>
        <div class="card">
          <% if computer.photos.attached? %>
            <%= cl_image_tag computer.photos.first.key, class: 'laptop-image' %>
          <% end %>
          <ul>
            <li> <%= computer.brand %> </li>
            <li> Useful for <%= computer.category %> </li>
            <li> <%= computer.screen_size %> inches </li>
            <li> <strong><%= computer.price %>€/day</strong> </li>
          </ul>
          <div class="container justify-content-center">
            <%= link_to "See more", computer_path(computer), class: "btn btn-outline-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-lewagon-black" data-navbar-target="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://img.freepik.com/free-vector/creative-computer-logo-template_23-2149213537.jpg?w=1380&t=st=1661420651~exp=1661421251~hmac=ac11b55132d026be3a0728488b6b3cb2ecc6248ada20ef03ad510b1545f141f7" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <%if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "default_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a laptop", new_computer_path, class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-flat" %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>